#!/usr/bin/env python3
"""Render the narration screens to Atari 2600 playfield data.

Emits src/text.inc: for each story screen, six planes of playfield
bytes (PF0L/PF1L/PF2L/PF0R/PF1R/PF2R) that the story kernel replays
line-by-line on the asymmetric 40-column playfield. Each text row is
a 3x5 font padded to 6 double-lines; every plane ends with one blank
byte the kernel uses for all non-text lines.

Usage: python3 tools/gentext.py src/text.inc
"""
import sys

# 3x5 font, rows top->bottom, 3 bits per row (MSB = left column)
FONT = {
    'A': [0b010, 0b101, 0b111, 0b101, 0b101],
    'B': [0b110, 0b101, 0b110, 0b101, 0b110],
    'C': [0b011, 0b100, 0b100, 0b100, 0b011],
    'D': [0b110, 0b101, 0b101, 0b101, 0b110],
    'E': [0b111, 0b100, 0b110, 0b100, 0b111],
    'F': [0b111, 0b100, 0b110, 0b100, 0b100],
    'G': [0b011, 0b100, 0b101, 0b101, 0b011],
    'H': [0b101, 0b101, 0b111, 0b101, 0b101],
    'I': [0b111, 0b010, 0b010, 0b010, 0b111],
    'J': [0b001, 0b001, 0b001, 0b101, 0b010],
    'K': [0b101, 0b110, 0b100, 0b110, 0b101],
    'L': [0b100, 0b100, 0b100, 0b100, 0b111],
    'M': [0b101, 0b111, 0b111, 0b101, 0b101],
    'N': [0b101, 0b111, 0b111, 0b111, 0b101],
    'O': [0b010, 0b101, 0b101, 0b101, 0b010],
    'P': [0b110, 0b101, 0b110, 0b100, 0b100],
    'Q': [0b010, 0b101, 0b101, 0b010, 0b001],
    'R': [0b110, 0b101, 0b110, 0b101, 0b101],
    'S': [0b011, 0b100, 0b010, 0b001, 0b110],
    'T': [0b111, 0b010, 0b010, 0b010, 0b010],
    'U': [0b101, 0b101, 0b101, 0b101, 0b111],
    'V': [0b101, 0b101, 0b101, 0b101, 0b010],
    'W': [0b101, 0b101, 0b111, 0b111, 0b101],
    'X': [0b101, 0b101, 0b010, 0b101, 0b101],
    'Y': [0b101, 0b101, 0b010, 0b010, 0b010],
    'Z': [0b111, 0b001, 0b010, 0b100, 0b111],
    '.': [0b000, 0b000, 0b000, 0b000, 0b010],
    ',': [0b000, 0b000, 0b000, 0b010, 0b100],
    "'": [0b010, 0b010, 0b000, 0b000, 0b000],
    '!': [0b010, 0b010, 0b010, 0b000, 0b010],
    '?': [0b110, 0b001, 0b010, 0b000, 0b010],
    ' ': [0, 0, 0, 0, 0],
}

# The 4K script (creative brief, terse 10-column form). One list of
# rows (max 10 chars) per screen.
SCREENS = [
    ["STELLA WAS", "  ALONE."],                             # before L1
    [" THERE HAD", "TO BE MORE"],                           # before L2
    [" AND THEN", "THERE WERE", "   TWO."],                 # before L3
    ["TOGETHER,", "THOUGH..."],                             # before L6
    ["THE WORLD", " SHIFTED.", "EXPANDED.", " CHANGED."],   # ending
]


def row_columns(text):
    """A text row -> 40 column bits (10 chars x 4 columns)."""
    text = text.upper().ljust(10)[:10]
    cols_by_line = []
    for line in range(5):
        cols = []
        for ch in text:
            glyph = FONT.get(ch, FONT[' '])[line]
            cols += [(glyph >> 2) & 1, (glyph >> 1) & 1, glyph & 1, 0]
        cols_by_line.append(cols)
    return cols_by_line  # 5 lines of 40 column bits


def encode(cols):
    """40 column bits -> (PF0L, PF1L, PF2L, PF0R, PF1R, PF2R)."""
    pf0l = sum(cols[i] << (4 + i) for i in range(4))            # c0-3
    pf1l = sum(cols[4 + i] << (7 - i) for i in range(8))        # c4-11
    pf2l = sum(cols[12 + i] << i for i in range(8))             # c12-19
    pf0r = sum(cols[20 + i] << (4 + i) for i in range(4))       # c20-23
    pf1r = sum(cols[24 + i] << (7 - i) for i in range(8))       # c24-31
    pf2r = sum(cols[32 + i] << i for i in range(8))             # c32-39
    return pf0l, pf1l, pf2l, pf0r, pf1r, pf2r


def build_screen(rows):
    """-> six plane byte-lists, each 6*R+1 long (blank line pads +
    one trailing blank byte for all non-text scanlines)."""
    planes = [[] for _ in range(6)]
    for row in rows:
        lines = row_columns(row)
        for line in lines:
            for p, b in enumerate(encode(line)):
                planes[p].append(b)
        for p in range(6):
            planes[p].append(0)  # 1 blank double-line between rows
    for p in range(6):
        planes[p].append(0)      # the kernel's "blank" index (6R)
    return planes


def main(out_path):
    lines = ["; generated by tools/gentext.py -- do not edit by hand"]
    strides, lens = [], []
    for i, rows in enumerate(SCREENS):
        planes = build_screen(rows)
        stride = len(planes[0])
        strides.append(stride)
        lens.append(stride - 1)  # 6R = index of the blank byte
        lines.append(f"Story{i}:  ; {' / '.join(r.strip() for r in rows)}")
        for p in planes:
            for j in range(0, len(p), 12):
                chunk = ",".join(f"${b:02x}" for b in p[j:j + 12])
                lines.append(f"        .byte {chunk}")
    lines.append("StoryLo:     .byte " + ",".join(f"<Story{i}" for i in range(len(SCREENS))))
    lines.append("StoryHi:     .byte " + ",".join(f">Story{i}" for i in range(len(SCREENS))))
    lines.append("StoryLen:    .byte " + ",".join(str(n) for n in lens))
    lines.append("StoryStride: .byte " + ",".join(str(s) for s in strides))
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    total = sum(s * 6 for s in strides)
    print(f"text.inc: {len(SCREENS)} screens, {total} bytes of playfield data")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "src/text.inc")
